Broadcasting

In [0]:
import numpy as np
p=np.array([[1.0,2.0,3.0,4.0]])
q=[[4]]
print(p+q)


[[5. 6. 7. 8.]]


linear algebra

In [0]:
#,Dot product
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2],[3,4],[5,6]])
print(a)
print(b)
print("dot: ",np.dot(a,b))
print("vdot: ",np.vdot(a,b))
#print("determinant: ",np.linalg.det(a))
#4xo+3x1=18 and xo+3x1=9
a=np.array([[4,3],[1,3]])
b=np.array([18,9])
x=np.linalg.solve(a,b)
#to verify the ans. np.allclose( np.dot(a,x),b) #we use all close for precision allclose check how close the value are compare element by element
print("x: ",x)
print("allcose: ",np.allclose( np.dot(a,x),b))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
dot:  [[22 28]
 [49 64]]
vdot:  91
x:  [3. 2.]
allcose:  True


Matrix Library

In [0]:
print(np.inf)
print(np.full((2,2),np.inf))
print( np.zeros( (2,),dtype=[('x','i4'),('y','i4')]) )
#full_like:
#zeros_like
#ones_like
print(np.empty_like(a))
print(np.empty([2,2]))

inf
[[inf inf]
 [inf inf]]
[(0, 0) (0, 0)]
[[9218868437227405312 9218868437227405312]
 [9218868437227405312 9218868437227405312]]
[[inf inf]
 [inf inf]]
