In [0]:
# to create complex numbers
[complex(a,b) for a,b in zip([1,2,3],[2,3,4]) ]


[(1+2j), (2+3j), (3+4j)]

In [0]:
import numpy as np
a=np.array([[3,2,1],[1,2,3]])
print(a.shape)

(2, 3)


In [0]:
import numpy  as np
a=np.array([[1,2,3],[4,5,6]])
print("Initial state: ",a)
a.shape=(3,2)
print(a)

Initial state:  [[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [0]:
import numpy  as np
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [0]:
#Question--- diff. between shape and reshape

In [0]:
import numpy  as np
a=np.array( [ [ [ [1,2,3] ,[4,5,6] ] ] ] ) #no. of square braces k saath dimension mai changes aayenge list k andr list k andr list to ye 4D bn gyi
print(a.ndim)

4


In [0]:
import numpy  as np
b=np.arange(24)
print(b) # it return 1D array from 0 to 23

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [0]:
import numpy  as np
a=np.arange(24)
b=a.reshape(2,4,3) #  3d array 2 is no. of sublists and 4 is no. of rows in ech sublist and 3 is no. of columns in each sublists
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [0]:
import numpy  as np
x=np.array([1,2,3,4,5],dtype=np.int64)
print(x.itemsize)

8


In [0]:
import numpy  as np
x=np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [0]:
x=[1,2,3]
a=np.asarray(x)
print(a.dtype)

int64


In [0]:
x=[1,2,3]
y=4,5,6
a=np.asarray(x,dtype=np.float64)
b=np.asarray(y)
print(a,b)

z=[(1,2,3),(4,5)]
print(z)
print(np.asarray(z))
print(np.asarray(z)[1][1])
print(type(a))

[1. 2. 3.] [4 5 6]
[(1, 2, 3), (4, 5)]
[(1, 2, 3) (4, 5)]
5
<class 'numpy.ndarray'>


In [0]:
import numpy as np
x=[1,2,3]
a=np.arange(10,20,5,float) #.2 is a step
print(a)

[10. 15.]


In [0]:
x=np.linspace(10,20,5,endpoint=False) #5 is number of steps
print(x)
print(type(x))
y=np.linspace(10,21,5,retstep=True) #5 steps hai to 2.5 2.5 ka ek ek step hoga 5 times
print(y)
print(type(y))

[10. 12. 14. 16. 18.]
<class 'numpy.ndarray'>
(array([10.  , 12.75, 15.5 , 18.25, 21.  ]), 2.75)
<class 'tuple'>


In [0]:
a=np.logspace(1,10,num=10,base=10) #finding logs between 10 and 100
print(a)
b=np.logspace(1,10,num=8,base=2)
print(b)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
[   2.            4.87605462   11.88795431   28.98315726   70.66172888
  172.27522466  420.01170228 1024.        ]


In [0]:
##20 jan 2020


In [0]:
import numpy as np
a=np.arange(10)
print(a)
s=slice(2,7,2)
print(s)
b=a[2::2]
c=a[5]
print(a[2:5])
print(c)
print(a[s],b)


[0 1 2 3 4 5 6 7 8 9]
slice(2, 7, 2)
[2 3 4]
5
[2 4 6] [2 4 6 8]


In [0]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("*********")
print(a[1:])
print("*********")
print(a[:1])
print("*********")
print(a[:2])
print("*********")
print(a[0,0])
print("*********")
print(a[2,2])
print("*********")
print(a[0:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
*********
[[4 5 6]
 [7 8 9]]
*********
[[1 2 3]]
*********
[[1 2 3]
 [4 5 6]]
*********
1
*********
9
*********
[[2 3]
 [5 6]
 [8 9]]


In [0]:
# ELLIPSIS :- when used at the row position it will return an ndarray

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("*******************")
print(a[...,1:]) #no rows specified, column 2 understood by default
print("**********")
print(a[1:,...])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
*******************
[[2 3]
 [5 6]
 [8 9]]
**********
[[4 5 6]
 [7 8 9]]


In [0]:
# integer indexing
x=np.array([[1,2],[4,5],[7,8]])
y=x[[0,1,2],[0,1,0]] #0th ka 0th element, 1st ka 1st element, 2nd ka 0th element
z=x[[2,0,1],[1,1,1]] #2nd ka 1st element, 0th ka 1st element, 1st ka 1st element
print(x)
print("*****")
print(y)
print("*****")
print(z)

[[1 2]
 [4 5]
 [7 8]]
*****
[1 5 7]
*****
[8 2 5]


In [0]:
#Field indexing
x=np.array([('REx',9,81.0),('Fido',3,27.0)], dtype=[('name','U5'),('age','i4'),('weight','f4')]) #U1 means only 1 character U2 means 2 characters U means 0 characters
print(x[0])
print(x['name'])
print(x['age']>5)
print(type(x['age']))
y=x['age']
print(y)
print(x)

('REx', 9, 81.)
['REx' 'Fido']
[ True False]
<class 'numpy.ndarray'>
[9 3]
[('REx', 9, 81.) ('Fido', 3, 27.)]


In [0]:
#example of integer indexing
import numpy as np
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)
print(x[[0,1],[1,2]])
print(x[[0,2],[1,2]])

#print(x[[3,0],[3,2]]) ### JHOL



[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[1 5]
[1 8]


In [0]:
y=x[1:4,[1,2]]
print(y)

[[ 4  5]
 [ 7  8]
 [10 11]]
