Statistical Functions of Numpy

In [0]:
#numpy.amin() and numpy.amax(),np.ptp()
import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9]])
wts=np.array([[1,2,3],[4,5,6],[7,8,9] ])
print(x)
print(np.amax(x))
print(np.amin(x))
print(np.ptp(x))
print(np.ptp(x,axis=0)) #column vise means across rows
print("*********")
print(np.ptp(x,axis=1)) #row vise
print("Percentile",np.percentile(x,40))
print("Median",np.median(x, axis=1))
print("average",np.average(x,weights=wts,axis=1))
print("average",np.average(x,weights=wts,axis=0))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
8
[6 6 6]
*********
[2 2 2]
Percentile 4.2
Median [2. 5. 8.]
average [2.33333333 5.13333333 8.08333333]
average [5.5 6.2 7. ]


Normal distribution mai mean median mode same hote hai 

mean median mai diff. aayega agr no. of observation even hai ya odd hai

mean can be an imaginary no. will not exist in the population where as median will diffinitely exist in the population



Standard deviation : how far each point is far from mean 

underroot (summition(xi - x')2)/x  where x' is mean

deviations ko sum krenge to 0 milega

In [0]:
print("Standard deviation: ", np.std(x) )

Variance

In [0]:
#square of standard deviations
print("Variance: ",)

change shape

1. reshape: 
2. flat
3. flatten
4. revel
5. ndarray.T: self.transpose
6. rollaxis: roll sthe specified axis backwards
7. swapaxis: interchanging the two axis
8. broadcast: produces an object that mimics broadcasting
9. broadcast_too: broadcasts an array to a new array
10. expand_dims: expand the shape of an array
11. squeeze: remove 1-d enteries from the shape of an array

12. concatenate
13. stack
14. hstack
15. vstack


16. split 
17. hsplit
18. vsplit

19. resize:
20. append:
21. insert
22. delete:
23. unique:


24. bitwise_and:
25. bitwise_or:
26. invert:
27. left_shift:
28. right_shift:

String functions:


1.   multiply()
2.   add()
3. center()
4. capitalize()
5. title()
6. lower()
7. upper()
8. split()
9. splitlines()
10. replace()
11. decode()
12. encode()




under what conditions median and mode should be used 
try to see where clusters are forming 
bias:

In [0]:
# Airthmatic functions
import numpy as np
a=np.arange(9,dtype=np.float_).reshape(3,3)
b=np.arange(10,19,dtype=np.float_).reshape(3,3)

c=a+b
d=a-b
e=a*b
f=a/b
print("a: ",a)
print("b: ",b)
print("c: ",c)
print("d: ",d)
print("e: ",e)
print("f: ",f)

a:  [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
b:  [[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
c:  [[10. 12. 14.]
 [16. 18. 20.]
 [22. 24. 26.]]
d:  [[-10. -10. -10.]
 [-10. -10. -10.]
 [-10. -10. -10.]]
e:  [[  0.  11.  24.]
 [ 39.  56.  75.]
 [ 96. 119. 144.]]
f:  [[0.         0.09090909 0.16666667]
 [0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444]]


In [0]:
print("reciprocal: ",np.reciprocal(a))
powr=np.array([[1,2,3],[4,5,6],[7,8,9]]).reshape(3,3)
print("power: ",np.power(a,powr))
print("mod: ",np.mod(a,powr))
print("remainder: ",np.remainder(a,powr))

reciprocal:  [[       inf 1.         0.5       ]
 [0.33333333 0.25       0.2       ]
 [0.16666667 0.14285714 0.125     ]]
power:  [[0.00000000e+00 1.00000000e+00 8.00000000e+00]
 [8.10000000e+01 1.02400000e+03 1.56250000e+04]
 [2.79936000e+05 5.76480100e+06 1.34217728e+08]]
mod:  [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
remainder:  [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.


Copy, view and deep copy

every thing in a python is objects.
id() returns the universal identifier of python objects


In [0]:
array=np.arange(4)
print("id of initial array: ",id(array))
barray=array
print(array)
print(barray)
x=id(array)
y=id(barray)
print("x: ",x,"y: ",y)
barray.shape = (2,2)
print("b: ",barray)
print("a: ",array)


id of initial array:  139756747546672
[0 1 2 3]
[0 1 2 3]
x:  139756747546672 y:  139756747546672
b:  [[0 1]
 [2 3]]
a:  [[0 1]
 [2 3]]
